
POST http://localhost:3000/auth/login HTTP/1.1 
content-type: application/json

{
    "email": "jurandir@gmail.com",
    "password" : "asdaada"
}

###

POST http://localhost:3000/auth/register HTTP/1.1 
content-type: application/json

{
    "name": "Jurandir",
    "email": "jurand3223dsa32ir@gmail.com",
    "password" : "asdaada"
}

###

DELETE http://localhost:3000/auth HTTP/1.1 


###
